import { FC, useState } from 'react';
import { Box } from '@mui/system';
import { Col, Container, Row } from 'react-bootstrap';
import { documentation } from './api';
import ApiDocumentationMenu from './ApiDocumentationMenu';
import ApiDocumentationEndpoint from './ApiDocumentationEndpoint';
import ApiDocumentationOverview from './ApiDocumentationOverview';

interface RestApiDocumentationAppProps {
  endpoints: documentation;
}

const ApiDocumentationApp: FC<RestApiDocumentationAppProps> = ({ endpoints }) => {
  const [activeEndpoint, setEndpoint] = useState<string>();
  const [menuOpen, setMenuOpen] = useState(true);
  const selectedEndpoint = endpoints.find((endpointItem) => endpointItem.class === activeEndpoint);

  return (
    <Box sx={{ margin: '1.5em 0' }}>
      <Container>
        <Row>
          <Col md={menuOpen ? 3 : 1}>
            <ApiDocumentationMenu
              endpoints={endpoints}
              activeEndpoint={activeEndpoint}
              isMenuOpen={menuOpen}
              setEndpoint={setEndpoint}
              setMenuOpen={() => setMenuOpen(!menuOpen)}
            />
          </Col>
          <Col>
            {selectedEndpoint ? (
              <ApiDocumentationEndpoint endpoint={selectedEndpoint} />
            ) : (
              <ApiDocumentationOverview endpoints={endpoints} setEndpoint={setEndpoint} />
            )}
          </Col>
        </Row>
        <Row>
          <Box sx={{ marginTop: 2 }}>
            Generated by&nbsp;
            <a href="https://github.com/baraja-core/structured-api-doc" target="_blank" rel="noreferrer">
              Baraja documentation
            </a>
            .
          </Box>
        </Row>
      </Container>
    </Box>
  );
};

export default ApiDocumentationApp;
