name: Build and test package

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --dev

      - name: Check TypeScript types
        run: yarn tsc --noEmit

      - name: Build package
        run: yarn build

      - name: Test package
        run: yarn test
